source("http://jonsmitchell.com/code/plotFxn02b.R")
head(Data)
plot(Data1$age,Data1$mass)
head(Data2)
cyrus<-Data2
Mass<-which(Data1[,9]=='trait_mass')
berenMass<-Data1[Mass,]
head<-(berenMass)
Mass<-which(Data1$event=='trait_mass')
Mass<-which(Data1[,9]=='trait_mass')
berenMilk<-Data1[Mass,]
head(berenMilk)
Mass<-which(Data1[,'event']=='trait_mass')
Mass<-which(Data1$event =='trait_mass')
dayID<-apply(Data1,1, function(x) paste(x[1:3], collapse='-'))
dateID<-sapply(dayID, as.Date, format="%Y-%m-%d", origin="2019-04-18")
Data1$age<-dateID-dateID[which(Data1$event=='birth')]
head(Data1)
beren2<-Data1
beren3<-beren2[order(beren2$age),]
write.csv(beren3, 'beren_new.csv', quote=F, row.names=FALSE)
Mass<-which(beren3$event=="trait_mass")
avgMilk<-mean(beren3$value[Mass])
avgMass<-tapply(beren3$value[Mass], beren3$age[Mass],mean)
varMass<-tapply(beren3$value[Mass],beren3$age[Mass],var)
totalMass<-tapply(beren3$value[Mass],beren3$age[Mass],sum)
numMass<-tapply(beren3$value[Mass],beren3$age[Mass],length)
cor(beren3$value[Mass],beren3$age[Mass])
cor.test(beren3$value[Mass],beren3$age[Mass])
berenCor<-cor.test(beren3$value[Mass],beren3$age[Mass])
summary(berenCor)
berenANOVA<-aov(beren3$value[Mass]~beren3$caregiver[Mass])
boxplot(beren3$value[Mass]~beren3$caregiver[Mass],xlab="age (days)",ylab="mass (kg)")
par(las=1,mar=c(5,5,1,1),mgp=c(2,0.5,0),tck=-0.01)
plot(as.numeric(names(totalMass)),totalMass,col="blue",type="p",ylim=c(0,20),pch=16,xlab="age (days)",ylab="mass (kg)")
points(cyrus3$value[cMass]/1000~cyrus3$age[cMass],type="p",pch=16,col="green",xlab="age (days)",ylab="mass (kg)")
title("Cyrus and Beren Age vs Mass")
legend(1000,5,legend=c("Beren", "Cyrus"),col=c("blue","green"),lty=1:1,cex=0.8,title="Kids",text.font=4,bg="yellow")
abline(h=mean(totalMass),lty=2,col='red')
pdf("r02b-totalMilkByDay2.pdf",height=4,width=4)
par(las=1,mar=c(5,5,1,1),mgp=c(2,0.5,0),tck=-0.01)
plot(as.numeric(names(totalMass)),totalMass,type="b",pch=16,xlab="age (days)",ylab="mass (kg)")
abline(h=mean(totalMass),lty=2,col='red')
dev.off()
Mass<-which(Data2[,9]=='trait_mass')
cyrusMass<-Data2[Mass,]
head<-(cyrusMass)
cMass<-which(Data2$event=='trait_mass')
cMass<-which(Data2[,9]=='trait_mass')
cyrusMilk<-Data2[Mass,]
head(cyrusMilk)
Mass<-which(Data2[,'event']=='trait_mass')
Mass<-which(Data2$event =='trait_mass')
dayID<-apply(Data2,1, function(x) paste(x[1:3], collapse='-'))
dateID<-sapply(dayID, as.Date, format="%Y-%m-%d", origin="2022-04-12")
Data2$age<-dateID-dateID[which(Data2$event=='birth')]
head(Data2)
cyrus2<-Data2
cyrus3<-cyrus2[order(cyrus2$age),]
write.csv(cyrus3, 'cyrus_new.csv', quote=F, row.names=FALSE)
cMass<-which(cyrus3$event=="trait_mass")
avgcMass<-tapply(cyrus3$value[cMass], cyrus3$age[cMass],mean)
varcMass<-tapply(cyrus3$value[cMass],cyrus3$age[cMass],var)
totalcMass<-tapply(cyrus3$value[cMass],cyrus3$age[cMass],sum)
numcMass<-tapply(cyrus3$value[cMass],cyrus3$age[cMass],length)
cor(cyrus3$value[cMass],cyrus3$age[cMass])
cor.test(cyrus3$value[cMass],cyrus3$age[cMass])
cyrusCor<-cor.test(cyrus3$value[cMass],cyrus3$age[cMass])
summary(cyrusCor)
cyrusANOVA<-aov(cyrus3$value[cMass]~cyrus3$age[cMass])
boxplot(cyrus3$value[cMass]/1000~cyrus3$caregiver[cMass], xlab="age (days)",ylab="mass (g)")
par(las=1,mar=c(5,5,1,1),mgp=c(2,0.5,0),tck=-0.01)
plot(as.numeric(names(totalMass)),totalMass,type="b",pch=16,xlab="age (days)",ylab="mass (g)")
abline(h=mean(totalMass),lty=2,col='red')
pdf("r02b-totalMilkByDay22.pdf",height=4,width=4)
par(las=1,mar=c(5,5,1,1),mgp=c(2,0.5,0),tck=-0.01)
plot(as.numeric(names(totalMass)),totalMass,type="b",pch=16,xlab="age (days)",ylab="mass (g)")
abline(h=mean(totalMass),lty=2,col='red')
dev.off()
